# Snakemake pipeline for QC and demultiplexing of Vilardo libraries
# by Josef Laurin, 2026

# Load configuration
# ------------------
configfile: "config/config.yaml"

import pandas as pd

# Sample wildcard constrains
wildcard_constraints:
    sample = "[^/]+"

# Parse sample names
samples_df = pd.read_csv(config["sample_table"], sep=",", dtype=str, encoding="utf-8-sig")
samples_df = samples_df.set_index("file_name", drop=False)
SAMPLES = samples_df["file_name"].tolist()

# All index names

BARCODES = ["I1", "I2", "I3", "I4", "I5", "I6", "I7", "I8"]

# Keeping only the ones specified in sample list

def get_keep_list(sample):
    digits = samples_df.loc[sample, "indexes"]  # e.g. "1234"
    return [f"I{d}" for d in digits]          # ["i1","i2","i3","i4"]

# Include rules
# -------------

include: "rules/demultiplex.smk"
include: "rules/qc.smk"



# Rules
# -----


rule all:
    default_target: True
    input:
        "results/multiqc_report.html",
        "results/read_distribution_plots.pdf",
        "results/read_distribution_table.csv"
    output:
        "get_all_results.txt"
    run:
        with open(str(output),"w") as file:
            for f in input:
                file.write(f+"\n")